<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'event' => '/Event.php',
                'licenserecognizedevent' => '/LicenseRecognizedEvent.php',
                'paytollcommand' => '/PayTollCommand.php',
                'paytollcommandhandler' => '/PayTollCommandHandler.php',
                'tollprepaidevent' => '/TollPrepaidEvent.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
